apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-data
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi