apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: redis-data
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi